### ISSUE TITLE
Invalid suggestions for templates using operator overload from macro expansion

### ISSUE THREAD

**Issue by graveljp** [include-what-you-use/include-what-you-use#1122]
IWYU provides invalid recommendation when a template uses an overloaded operator defined via a macro expansion. See here for a minimalist example reproducing this problem: https://github.com/graveljp/iwyu-bugs/tree/main/operator_overload_macro

You can reproduce by doing:
```
git clone https://github.com/graveljp/iwyu-bugs.git
cd iwyu-bugs/operator_overload_macro
include-what-you-use main.cc
```

This outputs:
```
main.cc should add these lines:
#include "my_int.h"  // for operator*

main.cc should remove these lines:

The full include-list for main.cc:
#include "my_int.h"  // for operator*
#include "utils.h"   // for TimesTen
---
```

`main.cc` shouldn't be including `my_int.h`. Interestingly, the problem doesn't happens if the `operator*` isn't defined by a macro in `my_int.h`, or if the `operator*` is replaced with a normal `Multiply()` function.

Tests at on latest master (IWYU at https://github.com/include-what-you-use/include-what-you-use/commit/c1d8dd310a3b2e0601d44ece73fba9bc037e82d1 and LLVM at https://github.com/llvm/llvm-project/commit/bc4bcbcfc820b324f680e8f260691c38052eedc9).

**Comment by graveljp** [comment]
It's worth pointing out that clangd (in [UnusedIncludes: Strict](https://clangd.llvm.org/guides/include-cleaner#configuration) mode) also agrees that `main.cc` shouldn't be including `my_int.h`.

**Comment by kimgr** [comment]
At verbosity level 5, IWYU will explain a little bit about its reasoning for use locations in macros. You can add `-Xiwyu -v5` and look for `Attributing use of ... to location at ...`. The preceding log lines cover the decision tree there.

If behavior is different with/without macro, I suspect it would mis-attribute the use of `MyInt` in a way that causes it to also run into the template instantiation problem space. Or something.

**Comment by graveljp** [comment]
I was able to get the same problem by replacing the macro invocation with an include statement to inject code in the header, though in that particular example, it means doing an `#include` at the end of a file, which is stretching it a bit:
```
struct MyInt {
  int value;
};
MyInt MakeMyInt(int value) {
  return {value};
}
#include "operations.h"
```
I found a different example that might be caused by the same problem. It still seems to be about operator overloads and templates, but this time, it doesn't rely on macros or misplaced includes. See at https://github.com/graveljp/iwyu-bugs/tree/main/operator_overload. Repro steps:
```
git clone https://github.com/graveljp/iwyu-bugs.git
cd iwyu-bugs/operator_overload
include-what-you-use main.cc
```

**Comment by kimgr** [comment]
Fixed on master as of a4ed455

**Comment by bolshakov-a** [comment]
The case with `// IWYU pragma: export` (https://github.com/include-what-you-use/include-what-you-use/issues/1122#issuecomment-1272592731) is not fixed.

**Comment by kimgr** [comment]
@bolshakov-a Thanks, I didn't see we had more than one thing going on here. Alright, let's reopen. The relevant bug test remains in https://github.com/include-what-you-use/include-what-you-use/blob/master/tests/bugs/1122/1122b.cc.
