### ISSUE TITLE
`<tuple>` suggested for `std::array` - confused by `<map>`

### ISSUE THREAD

**Issue by firewave** [include-what-you-use/include-what-you-use#1149]
```cpp
#include <array>
#include <cstddef>
#include <string>
#include <map> // removing this will get rid of the messages
#include <utility>

template<std::size_t N>
static void f(const std::array<std::pair<std::string, std::string>, N>&)
{
    std::map<int, int> m; // added so <map> is not unused
}
```

```
test.cpp should add these lines:
#include <tuple>    // for array

test.cpp should remove these lines:
- #include <array>  // lines 1-1

The full include-list for test.cpp:
#include <cstddef>  // for size_t
#include <map>      // for map
#include <string>   // for string
#include <tuple>    // for array
#include <utility>  // for pair
---
```

I am using `include-what-you-use 0.18 based on Debian clang version 14.0.6-2`.

**Comment by bolshakov-a** [comment]
I think it would be good if someone writes the symbol-to-header mapping file for the standard library, in addition to implementation-specific private-to-public header mappings. Or, even better, if someone writes a script to obtain it automatically from some standard library synopsis, if it is possible...

**Comment by Bu11etmagnet** [comment]
Somebody has already written such a thing, because GCC is able to print suggestions like "strcmp is defined in <string.h>, did you forget to include <string.h>?"

**Comment by kimgr** [comment]
@Bu11etmagnet Interesting. How comprehensive is it, e.g. does it suggest c++ library includes too? There may be licensing challenges with taking inspiration from GCC, I suppose.

**Comment by Bu11etmagnet** [comment]
Yes, it does: https://godbolt.org/z/vM6b5ndes

**Comment by kimgr** [comment]
Fixed on master as of https://github.com/include-what-you-use/include-what-you-use/commit/ffe6c3fe3a1dac9a4b577f4b07ef378ede933554 (and, as it turns out, before that).a

**Comment by Jackaed** [comment]
I'm still getting suggestions for `#include <tuple> // for array` on 0.22 @kimgr. Are you certain this is fixed?

**Comment by firewave** [comment]
I can confirm that the original example is not showing the issue with either libstdc++ or libc++.

@Jackaed this should be a new issue - best with a self-contained reproducer.

**Comment by firewave** [comment]
> I can confirm that the original example is not showing the issue with either libstdc++ or libc++.

But I have no pre-0.20 to verify that I can actually reproduce the issue...so take it with a grain of salt.
