### ISSUE TITLE
std::abs considered as built-in

### ISSUE THREAD

**Issue by avostrik** [include-what-you-use/include-what-you-use#776]
Hi,

Starting from branch clang_7.0 (0.11) up to the master following test incorrectly recommends to remove <cmath> include:

```
#include <cmath>

int main()
{
    float f = std::abs(-1.2f);
    return 0;
}
```

Output:

```
include-what-you-use testme.cpp -o testme -std=c++11

testme.cpp should add these lines:

testme.cpp should remove these lines:
- #include <cmath>  // lines 1-1

The full include-list for testme.cpp:
---
```

if cmath is removed by 'recommendation' code fails to compile with:

```
testme.cpp: In function ‘int main()’:
testme.cpp:5:20: error: ‘abs’ is not a member of ‘std’
     float f = std::abs(-1.2f);
                    ^~~
```

On prior versions it was ok, tracked it down to commit: e31cd2adda44729ad17df8446008935ae3f8b69e

If it is reverted, requires mapping for:
`{ symbol: [ "std::abs", private, "<cmath>", public ] }`
But I am not sure this is right way, as std::abs has overloads for integer types in `<cstdlib>`

**Comment by kimgr** [comment]
This portion here looks like where it could be misdiagnosed:
https://github.com/include-what-you-use/include-what-you-use/commit/e31cd2adda44729ad17df8446008935ae3f8b69e#diff-26cf66c7c7a592ef5761311019b0438cR1123

Can you turn up the log level (`-Xiwyu -v6`) and see if it's possible to determine which of those builtin checks discards `std::abs`?

**Comment by avostrik** [comment]
```
--- Calculating IWYU violations for testme.cpp ---
Ignoring use of std::abs (testme.cpp:5:15): built-in function
Ignoring use of std::abs (testme.cpp:5:15): built-in function
Ignoring use of std::abs (testme.cpp:5:15): built-in function

```

**Comment by kimgr** [comment]
@avostrik Thanks! I think I see what's going wrong -- `Builtin::Context::isBuiltinFunc` seems to be an aggregate check that doesn't take all characteristics of the builtin into account. More specifically, there seems to be a flag on each builtin that says `isHeaderDependentFunction`, which should indicate whether it's implicitly builtin or requires an include. We should probably weigh that into the analysis here.

**Comment by kimgr** [comment]
Oops, duplicated by #918, should be fixed by PR #920.

**Comment by firewave** [comment]
I can confirm that this is fixed.

**Comment by kimgr** [comment]
@firewave Thank you, tagged as fixed in IWYU 0.17.

**Comment by firewave** [comment]
FYI I only tested with back to 0.20 and those were obviously still showing #1000. With the last master there is no warning at all.
